// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenvConfig } from "dotenv";
// Load env files only when DATABASE_URL is not already set (e.g. passed inline for prod deploys).
// .env.local takes precedence over .env for local dev with Docker DB.
if (!process.env["DATABASE_URL"]) {
  dotenvConfig({ path: ".env.local", override: true });
  dotenvConfig();
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
