-- AlterTable
ALTER TABLE "ImageStats" ADD COLUMN IF NOT EXISTS "thumbsUp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ImageStats" ADD COLUMN IF NOT EXISTS "thumbsDown" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ImageStats" ADD COLUMN IF NOT EXISTS "reportCount" INTEGER NOT NULL DEFAULT 0;
